spring.config.activate.on-profile: local  #spring-boot 에서 구현하는 기능.
kdt:
  version: "v1.0"
  minimum-order-amount: 1
  support-vendors:
    - a
    - b
    - c
    - d
  description: |
    line 1 hello world
    line 2 xxxx
    line 3